# Generated by Django 5.0.4 on 2024-04-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agendas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("professor", models.CharField(max_length=100)),
                ("local", models.CharField(max_length=255)),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                        default="ativo",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
