# Generated by Django 5.0.4 on 2024-04-07 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_customuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
