# Generated by Django 5.0.4 on 2024-04-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[("aluno", "Aluno"), ("professor", "Professor")],
                default="aluno",
                max_length=20,
            ),
        ),
    ]
