# Generated by Django 5.0.4 on 2024-04-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_customuser_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agendas",
            name="status",
            field=models.CharField(
                choices=[("ativo", "Ativo"), ("inativo", "Inativo")],
                default="ativo",
                max_length=10,
                null=True,
            ),
        ),
    ]
